# Generated by Django 5.2.12 on 2026-03-12 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification_app', '0001_initial'),
        ('permission_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='permission_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permission_app.permissionrequest'),
        ),
    ]
