# Generated by Django 5.2.12 on 2026-03-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_class',
            field=models.CharField(blank=True, choices=[('ce1', 'CE1'), ('ce2', 'CE2'), ('it1', 'IT1'), ('it2', 'IT2'), ('aids', 'AIDS'), ('aids2', 'AIDS2'), ('ele1', 'ELE1'), ('ele2', 'ELE2'), ('mech1', 'MECH1'), ('mech2', 'MECH2'), ('entc1', 'ENTC1'), ('entc2', 'ENTC2')], max_length=10, null=True),
        ),
    ]
