# Generated by Django 6.0.3 on 2026-03-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0003_remove_application_completion_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='completion_certificate',
        ),
        migrations.RemoveField(
            model_name='application',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='application',
            name='offer_letter',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
        migrations.DeleteModel(
            name='PermissionRequest',
        ),
    ]
