# Generated by Django 6.0.3 on 2026-03-23 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_app', '0004_remove_application_completion_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='stipend_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
