# Generated by Django 5.2.12 on 2026-03-12 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internship_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending_faculty', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('completion_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_app.internship')),
            ],
        ),
    ]
