# Generated by Django 5.2.12 on 2026-03-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequest',
            name='status',
            field=models.CharField(choices=[('pending_faculty', 'Pending Faculty'), ('pending_hod', 'Pending HOD'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending_faculty', max_length=50),
        ),
    ]
